### ISSUE TITLE
Pinniped installed from `brew install pinniped-cli --HEAD` panics on `pinniped version`

### ISSUE THREAD

**Issue by mattmoyer** [vmware-tanzu/pinniped#541]
To reproduce:
- `brew tap vmware-tanzu/pinniped`
- `brew install pinniped-cli --HEAD`
- `pinniped version`

### Error
```
panic: version string "?.?.?" doesn't match expected regular expression: "^v(\d+\.\d+\.\d+)"

goroutine 1 [running]:
k8s.io/component-base/metrics.parseVersion(0x28c0bc0, 0x1, 0x28c0bc2, 0x1, 0x28c0c2c, 0x5, 0x2906020, 0x28, 0x28c0c24, 0x5, ...)
	/Users/moyerm/Library/Caches/Homebrew/go_mod_cache/pkg/mod/k8s.io/component-base@v0.0.0-20210329195309-e1576f54c4ca/metrics/version_parser.go:47 +0x2c5
k8s.io/component-base/metrics.newKubeRegistry(0x28c0bc0, 0x1, 0x28c0bc2, 0x1, 0x28c0c2c, 0x5, 0x2906020, 0x28, 0x28c0c24, 0x5, ...)
	/Users/moyerm/Library/Caches/Homebrew/go_mod_cache/pkg/mod/k8s.io/component-base@v0.0.0-20210329195309-e1576f54c4ca/metrics/registry.go:312 +0xfb
k8s.io/component-base/metrics.NewKubeRegistry(0x9, 0xc0006b0280)
	/Users/moyerm/Library/Caches/Homebrew/go_mod_cache/pkg/mod/k8s.io/component-base@v0.0.0-20210329195309-e1576f54c4ca/metrics/registry.go:327 +0x7f
k8s.io/component-base/metrics/legacyregistry.init()
	/Users/moyerm/Library/Caches/Homebrew/go_mod_cache/pkg/mod/k8s.io/component-base@v0.0.0-20210329195309-e1576f54c4ca/metrics/legacyregistry/registry.go:29 +0x26
```

**Comment by mattmoyer** [comment]
Seems fixed:
```
brew uninstall pinniped-cli && brew install pinniped-cli --HEAD && pinniped version
Uninstalling /usr/local/Cellar/pinniped-cli/HEAD-55bc3de... (5 files, 49.8MB)
==> Installing pinniped-cli from vmware-tanzu/pinniped
==> Cloning https://github.com/vmware-tanzu/pinniped.git
Updating /Users/moyerm/Library/Caches/Homebrew/pinniped-cli--git
==> Checking out branch main
Already on 'main'
Your branch is up to date with 'origin/main'.
HEAD is now at 55bc3dee Merge pull request #543 from mattmoyer/fix-head-version-string-validation

==> go build -o /usr/local/Cellar/pinniped-cli/HEAD-55bc3de/bin/pinniped -ldflags "$(hack/get-ldflags.sh)" cmd/pinniped/main.go
🍺  /usr/local/Cellar/pinniped-cli/HEAD-55bc3de: 5 files, 49.8MB, built in 13 seconds
version.Info{Major:"0", Minor:"0", GitVersion:"v0.0.0", GitCommit:"55bc3dee7f7e34c10379bb0f47b491791bc221e7", GitTreeState:"clean", BuildDate:"2021-03-31T21:56:35Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"darwin/amd64"}
```
